version: '3.1'

services:

  db:
    image: mysql
    restart: always
    ports:
       - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: aerolineas-usal
    volumes:
      - ./src/main/resources/db/demo.sql:/docker-entrypoint-initdb.d/Create-Demo.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
